resolver: lts-8.5

packages:
- '.'

extra-deps:
- Spock-digestive-0.3.0.0
- digestive-functors-0.8.1.1
- digestive-functors-lucid-0.0.0.4
- html-email-validate-0.2.0.0
- hasql-transaction-0.5

flags: {}

extra-package-dbs: []

